Repository itechart-warehouse/backend, pull requests merged in 2022-06, with the labels that each got.

#71 Feature/lw 7 pagination
  .gitignore
  .rspec
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/company_controller.rb
  app/controllers/concerns/paginatable.rb
  app/controllers/consignment_controller.rb
  app/controllers/user_controller.rb
  app/controllers/warehouse_controller.rb
  app/serializers/company_serializer.rb
  app/serializers/consignment_serializer.rb
  app/serializers/good_serializer.rb
  app/serializers/report_serializer.rb
  app/serializers/user_serializer.rb
  app/serializers/warehouse_serializer.rb
  config/database.yml
  config/routes.rb
  db/schema.rb
  spec/factories/companies.rb
  spec/factories/consignments.rb
  spec/factories/user_roles.rb
  spec/factories/users.rb
  spec/factories/warehouses.rb
  spec/rails_helper.rb
  spec/requests/companies_spec.rb
  spec/requests/consignments_spec.rb
  spec/requests/users_spec.rb
  spec/requests/warehouses_spec.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
  test/models/custom_audit_test.rb
Labels: On review

#74 hotfix LW-15 and LW-7
  Gemfile
  app/controllers/passwords_controller.rb
  app/mailers/devise_mailer.rb
  app/models/user.rb
  test/controllers/passwords_controller_test.rb
  test/mailers/devise_password_mailer_test.rb
Labels: bug, On review

#76 hotfix/lw-34-routes. Fix routes
  config/routes.rb
Labels: On review

#77 Hotfix/lw-38-fix
  app/controllers/company_controller.rb
  app/controllers/warehouse_controller.rb
  app/serializers/good_serializer.rb
Labels: On review

#81 feature/LW-25. Send birthday email
  Gemfile
  Gemfile.lock
  app/jobs/birthday_mailer_job.rb
  app/mailers/birthday_mailer.rb
  app/views/birthday_mailer/birthday_email.html.erb
  config/environments/test.rb
  config/sidekiq.yml
  spec/helpers/birthday_mailer_helper_spec.rb
  spec/jobs/birthday_mailer_job_spec.rb
Labels: On review, to deploy
